class-based-views/school/classroom/urls.py
from django.urls import path
from . import views

app_name='classroom'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('thank-you/', views.ThankYouView.as_view(), name='thank-you'),
    path('contact/', views.ContactFormView.as_view(), name='contact'),
    path('create-teacher/', views.TeacherCreateView.as_view(), name='create-teacher'),
    path('list-teacher/', views.TeacherListView.as_view(), name='list-teacher'),
]

class-based-views/school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

class-based-views/school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

def __str__(self):
    return f'{self.first_name} {self.last_name} teaches {self.subject}'

class-based-views/school/classroom/forms.py
from socket import fromshare
from django import forms

class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

class-based-views/school/classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView,FormView, CreateView, ListView
from django.urls import reverse_lazy
from classroom.forms import ContactForm
from classroom.models import Teacher
# Create your views here.

class HomeView(TemplateView):
    template_name =  'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    success_url = reverse_lazy('classroom:thank-you')

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class TeacherCreateView(CreateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:thank-you')

class TeacherListView(ListView):
    model = Teacher
    context_object_name = 'teacher_list'

class-based-views/school/classroom/templates/classroom/contact.html
<h1>Form View Template</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

class-based-views/school/classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>

<ul>

    <li><a href="{% url 'classroom:thank-you' %}">Thank you</a></li>
    <li><a href="{% url 'classroom:contact' %}">Contact</a></li>
    <li><a href="{% url 'classroom:create-teacher' %}">Create New Teacher</a></li>
    <li><a href="{% url 'classroom:list-teacher' %}">List Teacher</a></li>
</ul>

class-based-views/school/classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

class-based-views/school/classroom/templates/classroom/teacher_list.html
<h1>List of Teachers</h1>
<ul>
    {% for teacher in teacher_list %}
        <li>{{teacher.first_name}} {{teacher.last_name}}</li>
    {% endfor %}
</ul>

class-based-views/school/classroom/templates/classroom/thank_you.html
<h1>Thank you!</h1>